[project]
name = "crewai-tut"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crewai[google-genai]>=1.7.1",
    "dotenv>=0.9.9",
]
